---
- name: Delete site network device records from Infoblox
  hosts: network
  connection: local
  gather_facts: false

  vars:
    nios_provider:
      host: "{{ lookup('env', 'INFOBLOX_HOST') }}"
      username: "{{ lookup('env', 'INFOBLOX_USERNAME') }}"
      password: "{{ lookup('env', 'INFOBLOX_PASSWORD') }}"

  tasks:
    - name: Delete network object
      infoblox.nios_modules.nios_network:
        network: "{{ hostvars[inventory_hostname].site_cidr }}"
        state: absent
        provider: "{{ nios_provider }}"
      run_once: true

    - name: Delete site DNS zone
      infoblox.nios_modules.nios_zone:
        name: "{{ hostvars[inventory_hostname].dns_domain }}"
        state: absent
        provider: "{{ nios_provider }}"
      run_once: true

    - name: Delete site CIDR reverse zone
      infoblox.nios_modules.nios_zone:
        name: "{{ hostvars[inventory_hostname].site_cidr }}"
        zone_format: IPV4
        state: absent
        provider: "{{ nios_provider }}"
      run_once: true

...
